### PR TITLE
Draft: Repeater DB changes

### PR DESCRIPTION
**Pull request by dg0yt**
For feedback. (The whole C++ file. I didn't optimize for a minimal diff but for a better structure.)
In particular: caching. The download is app. 5 MB, and the server is taken several seconds to respond.

The class (or file) still has many responsibilities.
- Model for QML view
- Importer for repeater list
- Network access
- Positioning access and locator conversion

Positioning and locator conversion is used in the settings view, independent of the repeater list.
I would suggest ot break it up a little bit. Individual concerns could also be tested in CI (locator conversion, JSON import).

### CODE REVIEW

**Comment by dg0yt** [comment]
With the current qmake project structure, it is not possible to add any tests: Each target must be in a separate directory, but the main target is already at the top level. I know how to move things around at the plain text file level, but I don't know the impact on future interactive project changes in Qt Creator.

**Comment by myzinsky** [comment]
Best would be if we move the project to cmake ...

**Comment by dg0yt** [comment]
> Best would be if we move the project to cmake ...

Okay, I'm using CMake already since Qt5. It has some implications for generating bundle-style installations (ios and android app packages), and for IDE support (but I edit the cmake files directly).

**Comment by dg0yt** [comment]
> Best would be if we move the project to cmake ...

Started in https://github.com/myzinsky/cloudLogOffline/pull/120.

**Comment by myzinsky** [comment]
Just tell me when I should merge it :-)

**Comment by dg0yt** [comment]
I'm about to bring it in mergeable state. It fixes #119 which really deserves somes priority.

**Pull request merged**
