### PR TITLE
Add mode setting

### PR DESCRIPTION
**Pull request by Werzi2001**
It was a bit annoying for me that the mode was always set to SSB after finishing a QSO. Therefore I added a setting for the (similar to the frequency setting). Alternative to the setting it would have been possible to just not reset the mode after saving a QSO but as it was done using a setting for the frequency I thought that this would be the way to go here too.

### CODE REVIEW

**Comment by myzinsky** [comment]
"Betriebsart" is not the correct German term. It should be "Übertragungsverfahren" could you fix that? TNX

**Comment by Werzi2001** [comment]
@myzinsky Yes, no problem. Just wondering because I actually used the same translation as it was used for other labels as well:
https://github.com/myzinsky/cloudLogOffline/blob/master/translations/German.ts#L126
Should I change it everywhere?

**Comment by Werzi2001** [comment]
@myzinsky I changed the german translation. Just a bit worried because "Übertragungsverfahren" is quite a long word. Can't test it on mobile at the moment but I guess that >33% of the width are now used for the label.

One more thing:
I don't really like having the list of modes redundant in the code. I tried to extract it into a different file and reuse it but didn't find a working version. Especially when adding more modes/sub modes that might get frustrating/error prone to have a duplicate list. Do you know how to extract the model and only define it once?

**Comment by myzinsky** [comment]
@Werzi2001 I think the proper way would be to have a C++ based model which is used everywhere. But for now I accept this PR as it is. Maybe you could think about my suggestion.

**Pull request merged**
